backend:
  name: github
  repo: mharitonov429-art/mharitonov429-art.github.io
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Статьи"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Текст", name: "body", widget: "markdown"}
