site_url: https://медальпобеда.рф   # или Punycode: https://xn--80adafph4a9c.xn--p1ai
backend:
  name: github
  repo: mharitonov429-art/mharitonov429-art.github.io
  branch: main
  base_url: https://cms-proxy.decapi.org   # публичный прокси
  # auth_endpoint: /auth   # не требуется, прокси использует свой endpoint

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Страницы"
    folder: "/"
    extension: "html"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Контент", name: "body", widget: "markdown"}
